name: fooyin
base: core24
version: '0.10.4'
adopt-info: fooyin-app
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
grade: stable
confinement: strict
icon: org.fooyin.fooyin.svg

apps:
  fooyin:
    command: usr/bin/fooyin
    desktop: usr/share/applications/org.fooyin.fooyin.desktop
    common-id: org.fooyin.fooyin
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - home
      - removable-media
      - mount-observe
      - udisks2
    slots: [mpris]

plugs:
  shared-memory:
    private: true

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib

parts:
  fooyin-app:
    plugin: cmake
    source: https://github.com/fooyin/fooyin.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    parse-info: [dist/linux/org.fooyin.fooyin.metainfo.xml]
    build-packages:
      - libtag1-dev
      - libavfilter-dev
      - libxkbcommon-dev
      - libduktape207
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      craftctl default
      sed -i 's|Name=fooyin|Name=fooyin [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/org.fooyin.fooyin.desktop

  base-dependencies:
    after: [fooyin-app]
    plugin: nil
    stage-packages:
      - libavfilter9
      - libbs2b0
      - liblilv-0-0
      - libplacebo338
      - libpocketsphinx3
      - librubberband2
      - libserd-0-0
      - libsord-0-0
      - libsphinxbase3t64
      - libsratom-0-0
      - libvidstab1.1
      - libzimg2
      - libzix-0-0
      - libasound2t64
      - libasound2-plugins
      - libebur128-1
      - libsdl2-2.0-0
    prime:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfftw3_omp.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfftw3_threads.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_grapheme_lang.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_grapheme_lex.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_indic_lex.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_time_awb.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjacknet.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjackserver.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblcms2.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsphinxad.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libwayland-client.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_indic_lang.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_amdgpu.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_intel.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgallium*

  cleanup:
    after: [fooyin-app, base-dependencies]
    plugin: nil
    build-snaps:
      - mesa-2404
      - kf6-core24
    override-prime: |
      set -eux
      cd /snap/mesa-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/mesa-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

      cd /snap/kf6-core24/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/kf6-core24/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;
